version: '3.8'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node:react
    ports:
      - '80:3000'
    volumes:
      - '.:/usr/src/app'
    command: npm start