
PROJECT := js-reactions
SHELL   := /bin/bash
VERSION := 0.1.0

docker/build:
	@docker compose build --no-cache --force-rm

docker/up:
	@docker compose up -d

docker/down:
	@docker compose down --rmi all --volumes --remove-orphans

default: all

.PHONY:all
all:
	@docker compose -f .docker/docker-compose.yml build --no-cache --force-rm && docker compose -f .docker/docker-compose.yml up -d
	@echo
	@echo "Environment is up."
	@echo
